const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

// Set at build time (see .github/workflows/deploy_frontend.yml):
//  "api"    -- default. Talks to a real FastAPI backend at API_BASE_URL.
//  "static" -- GitHub Pages real-data demo. Reads real screening/backtest
//              output from static JSON files (frontend/public/data/*.json,
//              generated by backend/scripts/build_static_snapshot.py against
//              live vnstock data) instead of a live backend. Read-only --
//              there's no server to persist an Approve/Reject decision to.
//  "demo"   -- static fixture data (lib/sampleData.ts), for UI development
//              without needing either a backend or a live vnstock pull.
export type DataMode = "api" | "static" | "demo";
export const DATA_MODE: DataMode = (process.env.NEXT_PUBLIC_DATA_MODE as DataMode) || "api";
export const IS_READ_ONLY = DATA_MODE === "static";

export type PickStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface DailyStockPick {
  id: number;
  asset_id: number;
  ticker: string;
  company_name: string;
  pick_date: string;
  rationale: string;
  projected_sharpe: number;
  suggested_weight: number;
  backtest_summary: Record<string, unknown>;
  status: PickStatus;
  decided_at: string | null;
  decided_by: string | null;
}

export interface Holding {
  id: number;
  asset_id: number;
  ticker: string;
  quantity: number;
  avg_cost: number;
  opened_at: string;
  closed_at: string | null;
  peak_price_since_open: number;
  stop_loss_price: number | null;
  status: "OPEN" | "SELL_SIGNAL" | "CLOSED";
  sell_signal_reason: string | null;
}

export interface PerformanceSnapshot {
  id: number;
  snapshot_date: string;
  nav: number;
  sharpe_ratio: number | null;
  max_drawdown: number;
  factor_exposures: Record<string, number>;
  diagnostics: Record<string, unknown>;
}

export interface FlowAlert {
  id: number;
  asset_id: number;
  ticker: string;
  as_of_date: string;
  relative_volume: number;
  volume_zscore: number;
  price_change_pct: number;
  direction: "ACCUMULATION" | "DISTRIBUTION" | "NEUTRAL";
  foreign_net_value: number | null;
  is_anomalous: boolean;
  created_at: string;
}

export interface StaticSnapshotMeta {
  generated_at: string;
  universe: string[];
  universe_size: number;
  fetched_count: number;
  scoreable_count: number;
  disqualified_count: number;
  vif_dropped_factors: string[];
  factors: string[];
  walk_forward_folds: number | null;
  foreign_flow_history_days: number;
  note: string;
}

export interface RankedStock {
  ticker: string;
  sector: string;
  disqualified: boolean;
  disqualification_reasons: string[];
  composite_score: number | null;
  percentile_rank: number | null;
  factors_used_count: number;
  earnings_yield: number | null;
  book_to_market: number | null;
  ev_to_ebitda: number | null;
  roic: number | null;
  cfo_to_assets: number | null;
  interest_coverage: number | null;
  momentum: number | null;
  foreign_flow_5d: number | null;
  foreign_net_value_today: number | null;
  last_price: number | null;
  price_change_pct: number | null;
  relative_volume: number | null;
  volume_zscore: number | null;
  flow_direction: "ACCUMULATION" | "DISTRIBUTION" | "NEUTRAL" | null;
}

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE_URL}${path}`, {
    ...options,
    headers: { "Content-Type": "application/json", ...options?.headers },
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error(`API ${path} failed: ${res.status} ${await res.text()}`);
  }
  return res.json() as Promise<T>;
}

async function fetchStaticJson<T>(filename: string): Promise<T> {
  const res = await fetch(`${BASE_PATH}/data/${filename}`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(`Static snapshot ${filename} failed: ${res.status}`);
  }
  return res.json() as Promise<T>;
}

// Lazily imported so the sample fixtures never end up in a non-demo production
// bundle's initial chunk analysis just for being referenced at module scope.
async function loadDemoData() {
  return import("./sampleData");
}

let demoPicksCache: DailyStockPick[] | null = null;

export const getPicks = async (status?: PickStatus): Promise<DailyStockPick[]> => {
  if (DATA_MODE === "static") {
    const picks = await fetchStaticJson<DailyStockPick[]>("picks.json");
    return status ? picks.filter((p) => p.status === status) : picks;
  }
  if (DATA_MODE === "demo") {
    if (!demoPicksCache) {
      const { SAMPLE_PICKS } = await loadDemoData();
      demoPicksCache = SAMPLE_PICKS.map((p) => ({ ...p }));
    }
    return status ? demoPicksCache.filter((p) => p.status === status) : demoPicksCache;
  }
  return apiFetch<DailyStockPick[]>(`/api/picks${status ? `?status=${status}` : ""}`);
};

async function decideDemoPick(id: number, status: PickStatus, decidedBy: string): Promise<DailyStockPick> {
  if (!demoPicksCache) await getPicks();
  const pick = demoPicksCache!.find((p) => p.id === id);
  if (!pick) throw new Error(`Demo pick ${id} not found`);
  pick.status = status;
  pick.decided_at = new Date().toISOString();
  pick.decided_by = decidedBy;
  return { ...pick };
}

export const approvePick = (id: number, decidedBy = "user") => {
  if (DATA_MODE === "static") {
    throw new Error("Read-only real-data snapshot: there is no backend to persist an approval to.");
  }
  return DATA_MODE === "demo"
    ? decideDemoPick(id, "APPROVED", decidedBy)
    : apiFetch<DailyStockPick>(`/api/picks/${id}/approve`, {
        method: "POST",
        body: JSON.stringify({ decided_by: decidedBy }),
      });
};

export const rejectPick = (id: number, decidedBy = "user") => {
  if (DATA_MODE === "static") {
    throw new Error("Read-only real-data snapshot: there is no backend to persist a rejection to.");
  }
  return DATA_MODE === "demo"
    ? decideDemoPick(id, "REJECTED", decidedBy)
    : apiFetch<DailyStockPick>(`/api/picks/${id}/reject`, {
        method: "POST",
        body: JSON.stringify({ decided_by: decidedBy }),
      });
};

export const getHoldings = async (): Promise<Holding[]> => {
  if (DATA_MODE === "static") return fetchStaticJson<Holding[]>("holdings.json");
  if (DATA_MODE === "demo") {
    const { SAMPLE_HOLDINGS } = await loadDemoData();
    return SAMPLE_HOLDINGS;
  }
  return apiFetch<Holding[]>("/api/holdings");
};

export const getPerformanceHealth = async (limit = 180): Promise<PerformanceSnapshot[]> => {
  if (DATA_MODE === "static") {
    const perf = await fetchStaticJson<PerformanceSnapshot[]>("performance.json");
    return perf.slice(-limit);
  }
  if (DATA_MODE === "demo") {
    const { SAMPLE_PERFORMANCE } = await loadDemoData();
    return SAMPLE_PERFORMANCE.slice(-limit);
  }
  return apiFetch<PerformanceSnapshot[]>(`/api/performance/health?limit=${limit}`);
};

export const getFlowAlerts = async (days = 7, onlyAnomalous = true): Promise<FlowAlert[]> => {
  if (DATA_MODE === "static") {
    const alerts = await fetchStaticJson<FlowAlert[]>("flow_alerts.json");
    return onlyAnomalous ? alerts.filter((a) => a.is_anomalous) : alerts;
  }
  if (DATA_MODE === "demo") {
    const { SAMPLE_FLOW_ALERTS } = await loadDemoData();
    return onlyAnomalous ? SAMPLE_FLOW_ALERTS.filter((a) => a.is_anomalous) : SAMPLE_FLOW_ALERTS;
  }
  return apiFetch<FlowAlert[]>(`/api/flow-alerts?days=${days}&only_anomalous=${onlyAnomalous}`);
};

export const getSnapshotMeta = async (): Promise<StaticSnapshotMeta | null> => {
  if (DATA_MODE !== "static") return null;
  return fetchStaticJson<StaticSnapshotMeta>("meta.json");
};

// NOTE: no live-DB-backed FastAPI implementation of this endpoint exists yet
// (see README "What's real vs. what's a v1 foundation") -- the per-ticker
// rankings table is currently only produced by the static snapshot path.
// Calling this in "api" mode will 404 until that's built.
export const getRankings = async (): Promise<RankedStock[]> => {
  if (DATA_MODE === "static") return fetchStaticJson<RankedStock[]>("rankings.json");
  if (DATA_MODE === "demo") {
    const { SAMPLE_RANKINGS } = await loadDemoData();
    return SAMPLE_RANKINGS;
  }
  return apiFetch<RankedStock[]>("/api/rankings");
};
